services:
  postgres:
    image: postgres:17
    container_name: main_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5

  auth-service:
    build: ./auth-service
    restart: unless-stopped
    env_file:
      - ./auth-service/.env
    ports:
      - "${AUTH_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./auth-service:/app
      - /app/tmp
    command: air -c air.toml

  product-service:
    build: ./product-service
    restart: unless-stopped
    env_file:
      - ./product-service/.env
    ports:
      - "${PRODUCT_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./product-service:/app
      - /app/tmp
    command: air -c air.toml

  payment-service:
    build: ./payment-service
    restart: unless-stopped
    env_file:
      - ./payment-service/.env
    ports:
      - "${PAYMENT_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./payment-service:/app
      - /app/tmp
    command: air -c air.toml

  order-service:
    build: ./order-service
    restart: unless-stopped
    env_file:
      - ./order-service/.env
    ports:
      - "${ORDER_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./order-service:/app
      - /app/tmp
    command: air -c air.toml

volumes:
  pgdata:
