root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -v -o ./tmp/main ./cmd/main.go"
  entrypoint = "./tmp/main"
  full_bin = ""
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  include_dir = ["cmd", "internal"]
  delay = 1000
  stop_on_error = true
  poll = true
  poll_interval = 500

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = false